
default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: space_pirate
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: space_pirate

test:
  <<: *default
  database: space_pirate_test

production:
  <<: *default
  database: space_pirate